version: '3'
services:
  app:
    platform: linux/amd64
    build: .
    ports:
      - "8090:8090"
    volumes:
      - ./data.parquet:/data.parquet
    deploy:
      resources:
        limits:
          memory: 1024m
  prom-pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false
