{
 "title": "Go Processes",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(process_resident_memory_bytes{}, service)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=~\"^($service)$\"}",
     "legendFormat": "{{service}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{service=~\"^($service)$\"}",
     "legendFormat": "{{service}} - virtual"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{service=~\"^($service)$\"}[$interval])",
     "legendFormat": "{{service}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{service=~\"^($service)$\"}[$interval])",
     "legendFormat": "{{service}} - virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{service=~\"^($service)$\"}",
     "legendFormat": "{{service}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{service=~\"^($service)$\"}[30s])",
     "legendFormat": "{{service}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{service=~\"^($service)$\"}",
     "legendFormat": "{{service}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{service=~\"^($service)$\"}",
     "legendFormat": "{{service}} - heap inuse"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{service=~\"^($service)$\"}[$interval])",
     "legendFormat": "{{service}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{service=~\"^($service)$\"}[$interval])",
     "legendFormat": "{{service}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{service=~\"^($service)$\"}[$interval])",
     "legendFormat": "{{service}} - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{service=~\"^($service)$\"}[$interval])",
     "legendFormat": "{{service}} - heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{service=~\"^($service)$\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{service=~\"^($service)$\"}[$interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{service=~\"^($service)$\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{service=~\"^($service)$\"}[1m])",
     "legendFormat": "{{service}}: {{quantile}}"
    }
   ]
  },
  {
   "title": "GC Counts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{service=~\"^($service)$\"}[1m])",
     "legendFormat": "{{service}}: {{quantile}}"
    }
   ]
  }
 ]
}