global:
  scrape_interval: 10s
  scrape_timeout: 1s
  evaluation_interval: 10s

scrape_configs:
  - job_name: python
    metrics_path: /
    scheme: http
    static_configs:
      - targets: ['reference:8000']
        labels:
          service: duckdb-python
          language: python
  - job_name: golang
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['app:8090']
        labels:
          service: 'duckdb-golang'
          language: golang
